service: vrc-status-sync

custom:
  defaultStage: dev

provider:
  name: aws
  runtime: provided
  timeout: 300
  region: ap-northeast-1
  ecr:
    images:
      appImage:
        path: ./
        platform: linux/amd64
  stage: ${opt:stage, self:custom.defaultStage}
  environment: ${file(./env.yml)}

functions:
  vrc_status_sync:
    image:
      name: appImage
      command:
        - handler
    events:
      - schedule: rate(5 minute)
