service: vrc-status-sync

custom:
  defaultStage: dev

provider:
  name: aws
  runtime: provided
  timeout: 900
  region: ap-northeast-1
  ecr:
    images:
      appImage:
        path: ./
        platform: linux/amd64
  stage: ${opt:stage, self:custom.defaultStage}
  environment: ${file(./env.yml)}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::vrc-status-sync-data-${self:provider.stage}
            - arn:aws:s3:::vrc-status-sync-data-${self:provider.stage}/*

functions:
  vrc_status_sync:
    image:
      name: appImage
      command:
        - handler
    events:
      # JSTで18:00~02:00の間で1時間ごとに実行
      - schedule: cron(0 18-2 * * *)

resources:
  Resources:
    StatusSyncBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: vrc-status-sync-data-${self:provider.stage}